fixed linting error and added reporting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,8 +15,8 @@ jobs:
     name: Run PyTest with uv on Python ${{ matrix.python-version }}
     runs-on: ubuntu-latest
     strategy:
-      matrix:
-        python-version: ["3.11", "3.12", "3.13"]
+        matrix:
+          python-version: ["3.11", "3.12", "3.13"]
 
     steps:
     - name: Checkout code
@@ -25,12 +25,20 @@ jobs:
     # https://github.com/astral-sh/setup-uv
     - name: Install the latest version of uv
       uses: astral-sh/setup-uv@v7
+      with:
+        enable-cache: true
 
     - name: Set up Python ${{ matrix.python-version }}
-      uses: uv python install ${{ matrix.python-version }}
+      run: uv python install ${{ matrix.python-version }}
 
     - name: Install dependencies
       run: uv sync --all-extras --dev
 
     - name: Run PyTest
-      run: uv run pytest --junitxml=test-results.xml
+      run: uv run pytest --junitxml=test-results-${{ matrix.python-version }}.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure()  # Run this even if tests fail
+      with:
+        report_paths: 'test-results-*.xml'
